### ISSUE TITLE
The provided API key is invalid

### ISSUE THREAD

**Issue by Akari2512** [hoc081098/WeatherApp_MVI_sample#72]
I used the API key from openweathermap but when I tried to search for a destination it showed the error The The provided API key is invalid
PLACE_API_KEY = 196b0d55591caf98cbacfe0f2ebdd73d I put it in the local.properties like that but it still didn't work.
Can you help me?

**Comment by hoc081098** [comment]
PLACE_API_KEY is taken from google, not openweathermap.
https://developers.google.com/maps/documentation/places/web-service/get-api-key
